"""empty message

Revision ID: c1f54c1366ca
Revises: cc7ff12219c2
Create Date: 2020-11-14 15:20:05.349619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1f54c1366ca'
down_revision = 'cc7ff12219c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('genesis', sa.DateTime(), nullable=True))
    op.alter_column('usuario', 'highscore',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuario', 'highscore',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('usuario', 'genesis')
    # ### end Alembic commands ###
