"""empty message

Revision ID: cc7ff12219c2
Revises: f5967304ae0a
Create Date: 2020-11-14 12:21:10.014905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc7ff12219c2'
down_revision = 'f5967304ae0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuario', 'highscore',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuario', 'highscore',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
